config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#index'
  get '/contacto', to: 'pages#contacto'
  get '/articulo', to: 'pages#articulo'
  get '/articulo/new', to: 'pages#new'
  post '/articulo', to: 'pages#create'

  #delete '/articulo/:id',   to: 'pages#delete'
  #patch '/articulo/:id',    to: 'pages#editar'
  get '/articles/:id',      to: 'pages#ver', as: :articles
  #get '/articulo/:id/edit', to: 'pages#edit', as: :edit_articulo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/articulo.rb
class Articulo < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    paginates_per 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  
  end

  def contacto
  
  end

  def articulo
    #@articulo = Articulo.all
    @articulo = Articulo.order(:articulo).page(params[:page])
  end
  
  def new
    @articulo = Articulo.new
  end
  
  def create
   # data_articulo = params.require(:articulo).permit(:titulo, :contenido)
   # @articulo = Articulo.new(data_articulo)
   @articulo = Articulo.new(article_params)
    if @articulo.save
        redirect_to articulo_path
    else
        render :new
    end
  end

end

def show
    @articulo = Articulo.find(params[:id])
end
  

def edit
    @articulo = Articulo.find(params[:id])
end
  

def update
    @articulo = Articulo.find(params[:id])
      if @articulo.update(articulo_params)
          redirect_to articulos_path, notice: 'Articulo actualizado'
      else
        render :edit, status: :unprocessable_entity 
      end
 end
  

def delete
  @articulo = Articulo.find(params[:id])
  @articulo.destroy
  redirect_to articulos_path, notice: 'Articulo eliminado satisfactoriamente'
end
  

private
  
def articulo_params
  params.require(:articulo).permit(:titulo, :contenido)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Alejandro Gonzalez</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Blog de prueba<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contacto">Contacto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/articulo">Articulo</a>
      </li>
      <li class="nav-item">
        <a href="https://github.com/Agonzahe">
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 24 24" style="fill: rgb(60, 60, 60);transform: ;msFilter:;"><path fill-rule="evenodd" clip-rule="evenodd" d="M12.026 2c-5.509 0-9.974 4.465-9.974 9.974 0 4.406 2.857 8.145 6.821 9.465.499.09.679-.217.679-.481 0-.237-.008-.865-.011-1.696-2.775.602-3.361-1.338-3.361-1.338-.452-1.152-1.107-1.459-1.107-1.459-.905-.619.069-.605.069-.605 1.002.07 1.527 1.028 1.527 1.028.89 1.524 2.336 1.084 2.902.829.091-.645.351-1.085.635-1.334-2.214-.251-4.542-1.107-4.542-4.93 0-1.087.389-1.979 1.024-2.675-.101-.253-.446-1.268.099-2.64 0 0 .837-.269 2.742 1.021a9.582 9.582 0 0 1 2.496-.336 9.554 9.554 0 0 1 2.496.336c1.906-1.291 2.742-1.021 2.742-1.021.545 1.372.203 2.387.099 2.64.64.696 1.024 1.587 1.024 2.675 0 3.833-2.33 4.675-4.552 4.922.355.308.675.916.675 1.846 0 1.334-.012 2.41-.012 2.737 0 .267.178.577.687.479C19.146 20.115 22 16.379 22 11.974 22 6.465 17.535 2 12.026 2z"></path>
        </svg>
        </a>
      </li>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog de Prueba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section class="content">
       <%= render 'layouts/navbar'%>
     <%# <%= render 'shared/navbar'%>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    </section>
  </body>
</html>

app/views/pages/articulo.html.erb
<h2 class="title-contact">Todos los Articulos</h2>
<%= link_to "Nuevo Articulo", articulo_new_path, class: 'btn btn-primary' %><br>
<br>
<h3 style="color: green"><%= notice %></h3>
<br>
<%= paginate @articulo %>
<br>

<% @articulo.each do |art| %>
  <h3 class='movies'>Titulo: <span><%= art.titulo %></span></h3>
  <h3 class='movies'>Contenido: <span><%= art.contenido %></span></h3>
<br> 
<br> 
<% end %> 
<%# <%= link_to "Ver articulo", articles_path(art.id), class: 'btn btn-primary' %><br> %>

<br> 
<%= paginate @articulo %>

app/views/pages/contacto.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Plantilla básica de Bootstrap</title>

    <!-- CSS de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      
    </style>
  </head>
   <body>     
          <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="well well-sm">
                        <form class="form-horizontal" method="post">
                            <fieldset>
                                <legend class="text-center header">Formulario de Contacto</legend>

                                <div class="form-group">
                                    <span class="col-md-1 col-md-offset-2 text-center">
                                    <i class="fa fa-user bigicon"></i></span>
                                    <div class="col-md-8">
                                        <input id="fname" name="name" type="text" placeholder="Ingrese Su Nombre" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                                    <div class="col-md-8">
                                        <input id="lname" name="name" type="text" placeholder="Ingrese Su Apellido" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
                                    <div class="col-md-8">
                                        <input id="email" name="email" type="text" placeholder="Ingrese Correo" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                                    <div class="col-md-8">
                                        <input id="phone" name="phone" type="text" placeholder="Ingrese telefono" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                                    <div class="col-md-8">
                                        <textarea class="form-control" id="message" name="Ingrese Mensaje" placeholder="Introduzca su mesaje para nosotros aquí. Nos pondremos en contacto con usted a la brevedad posible." rows="7"></textarea>
                                    </div>
                                </div><br>

                                <div class="form-group">
                                    <div class="col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary btn-lg">Enviar</button>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      <script src="http://code.jquery.com/jquery.js"></script>
  </body>
</html>

app/views/pages/editar.html.erb
<h1 class="title-contact">Editar</h1>

<%= render 'shared/form' %>

app/views/pages/index.html.erb
<section>
  <div class="container">
    <p class="personal">Alejandro González Herrera, De profesión Ingeniero en Informatica y padre de familia.</p>
  </div>
</section>
<section>
  <div class="center">
    <%= image_tag 'dj.jpg'%>
    <p>Mis hobbies son Drones - Música - Tenis - Futbol - Docencia</p>
  </div>
  <div class="pasiones">
    <p>Mi pasion es en mis ratos libres de desconexion mezclar Música</p>
  </div>
</section>

app/views/pages/new.html.erb
<h1 class="title-contact">Incorporar Nuevo</h1>

<%= render 'shared/form' %>

app/views/pages/ver.html.erb
<h1 class='movies'>Articulo: <span><%= @articulo.titulo %></span></h1>
<p class='movies'><%= @articulo.contenido %></p>

<div>
  <%= link_to "Volver a articulos", articulo_path, class: 'btn btn-primary' %>
  <%= link_to "Editar el articulo", editar_articulo_path, class: 'btn btn-primary' %>
</div>
<br>
<%= button_to "Eliminar Articulo", articulo_path, method: :delete, class: 'btn btn-primary' %>

app/views/shared/_fomulario.html.erb
<%= form_with model: @articulo, class: 'form' do |form| %>
  <div class="form-group">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :contenido %>
    <%= form.text_area :contenido, class: 'form-control' %>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to "Volver al articulo", articulo_path, class: 'btn btn-primary' %>